# Generated by Django 2.2.2 on 2019-06-29 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=10)),
                ('year', models.CharField(choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('4', 'Fourth'), ('5', 'Fifth')], max_length=10)),
                ('semester', models.CharField(choices=[('1', 'First'), ('2', 'Second'), ('3', 'Recess')], max_length=10)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Program')),
                ('students', models.ManyToManyField(blank=True, related_name='courses_enroled', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
