# Generated by Django 2.2.2 on 2019-07-06 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_program_students'),
        ('student', '0003_auto_20190706_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.Program'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.University'),
            preserve_default=False,
        ),
    ]
