# Generated by Django 2.2.2 on 2019-06-29 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('abbreviation', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='university/picture/%Y/%m/%d')),
                ('display_picture', models.ImageField(blank=True, null=True, upload_to='university/display_picture/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('abbreviation', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='university/picture/%Y/%m/%d')),
                ('display_picture', models.ImageField(blank=True, null=True, upload_to='university/display_picture/%Y/%m/%d')),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('abbreviation', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('display_picture', models.ImageField(blank=True, null=True, upload_to='program/display_picture/%Y/%m/%d')),
                ('durations', models.PositiveIntegerField()),
                ('slug', models.SlugField(unique=True)),
                ('collage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Collage')),
            ],
        ),
        migrations.AddField(
            model_name='collage',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_collages', to='university.University'),
        ),
    ]
