# Generated by Django 2.2.2 on 2019-07-06 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_program_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='students',
        ),
    ]
